[styleTitle]
StringAlign=Center
StringCase=Upper
FontEffectColor=0,0,0,50
FontColor=#textColor#
FontFace=#fontName#
FontSize=10
AntiAlias=1
ClipString=1

[styleLeftText]
StringAlign=Left
StringCase=None
FontEffectColor=0,0,0,20
FontColor=#textColor#
FontFace=#fontName#
FontSize=#textSize#
AntiAlias=1
ClipString=1

[styleRightText]
StringAlign=Right
StringCase=None
FontEffectColor=0,0,0,20
FontColor=#textColor#
FontFace=#fontName#
FontSize=#textSize#
AntiAlias=1
ClipString=1

[styleBar]
BarColor=#barColor#
BarOrientation=HORIZONTAL
SolidColor=#bgMeterColor#